# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmFUX1JPeOAldE2chBtwut4akR73slEW
"""

!pip install streamlit -q

import streamlit as st
from datetime import date

# =========================================================
# PAGE CONFIGURATION
# =========================================================

st.set_page_config(
    page_title="SmartSpace",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =========================================================
# CUSTOM CSS
# =========================================================

st.markdown("""
<style>

html, body, [class*="css"] {
    font-family: "Segoe UI", sans-serif;
}

.stApp {
    background-color: #f7f9fc;
    color: #111827;
}

.block-container {
    padding-top: 2rem;
    padding-bottom: 2rem;
}

/* Sidebar */

section[data-testid="stSidebar"] {
    background-color: #111827;
}

section[data-testid="stSidebar"] * {
    color: #ffffff !important;
}

/* Main headings */

.main-title {
    font-size: 36px;
    font-weight: 700;
    color: #111827 !important;
    margin-bottom: 4px;
}

.subtitle {
    font-size: 16px;
    color: #64748b !important;
    margin-bottom: 28px;
}

/* KPI cards */

.kpi-card {
    background: #ffffff;
    padding: 22px;
    border-radius: 16px;
    border: 1px solid #e2e8f0;
    box-shadow: 0 4px 14px rgba(15, 23, 42, 0.05);
}

.kpi-title {
    font-size: 14px;
    color: #64748b !important;
    margin-bottom: 8px;
}

.kpi-value {
    font-size: 30px;
    font-weight: 700;
    color: #111827 !important;
}

/* Section headings */

.section-title {
    font-size: 22px;
    font-weight: 650;
    color: #111827 !important;
    margin-top: 30px;
    margin-bottom: 18px;
}

/* Room cards */

.room-card {
    background: #ffffff;
    padding: 20px;
    border-radius: 16px;
    border: 1px solid #e2e8f0;
    box-shadow: 0 3px 12px rgba(15, 23, 42, 0.04);
    margin-bottom: 14px;
}

.room-name {
    font-size: 19px;
    font-weight: 650;
    color: #111827 !important;
    margin-bottom: 8px;
}

.room-info {
    font-size: 14px;
    color: #64748b !important;
    margin-top: 5px;
}

.status-available {
    color: #15803d !important;
    font-weight: 600;
}

.status-busy {
    color: #dc2626 !important;
    font-weight: 600;
}

/* Streamlit widgets */

label {
    color: #334155 !important;
}

.stTextInput input,
.stNumberInput input {
    color: #111827 !important;
}

.stDateInput input,
.stTimeInput input {
    color: #111827 !important;
}

</style>
""", unsafe_allow_html=True)


# =========================================================
# DEMO DATA
# =========================================================

rooms = [
    {
        "name": "Room A",
        "capacity": 4,
        "projector": False,
        "whiteboard": False
    },
    {
        "name": "Room B",
        "capacity": 8,
        "projector": True,
        "whiteboard": False
    },
    {
        "name": "Room C",
        "capacity": 12,
        "projector": True,
        "whiteboard": True
    },
    {
        "name": "Room D",
        "capacity": 20,
        "projector": True,
        "whiteboard": True
    }
]

meetings = [
    {
        "title": "Project Discussion",
        "time": "09:00 - 10:00",
        "room": "Room B",
        "participants": 5
    },
    {
        "title": "Team Meeting",
        "time": "09:30 - 11:00",
        "room": "Room A",
        "participants": 3
    },
    {
        "title": "Client Presentation",
        "time": "10:00 - 11:30",
        "room": "Room C",
        "participants": 10
    },
    {
        "title": "Placement Preparation",
        "time": "11:00 - 12:00",
        "room": "Room B",
        "participants": 6
    },
    {
        "title": "Interview Session",
        "time": "11:30 - 12:30",
        "room": "Room C",
        "participants": 6
    }
]


# =========================================================
# SIDEBAR
# =========================================================

with st.sidebar:

    st.markdown("## 🏢 SmartSpace")
    st.caption("Intelligent Meeting Management")

    st.markdown("---")

    page = st.radio(
        "Navigation",
        [
            "📊 Dashboard",
            "📅 Meetings",
            "🏢 Rooms",
            "🔍 Search",
            "⚙️ Settings"
        ]
    )

    st.markdown("---")

    st.caption("Smart Meeting Room Allocation")
    st.caption("Powered by Python • SQLite • DSA")


# =========================================================
# DASHBOARD
# =========================================================

if page == "📊 Dashboard":

    st.markdown(
        '<div class="main-title">Good morning 👋</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">Here is your meeting room overview for today.</div>',
        unsafe_allow_html=True
    )

    # KPI CARDS

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown(
            '<div class="kpi-card">'
            '<div class="kpi-title">Total Meetings</div>'
            '<div class="kpi-value">7</div>'
            '</div>',
            unsafe_allow_html=True
        )

    with col2:
        st.markdown(
            '<div class="kpi-card">'
            '<div class="kpi-title">Total Rooms</div>'
            '<div class="kpi-value">4</div>'
            '</div>',
            unsafe_allow_html=True
        )

    with col3:
        st.markdown(
            '<div class="kpi-card">'
            '<div class="kpi-title">Booked Rooms</div>'
            '<div class="kpi-value">3</div>'
            '</div>',
            unsafe_allow_html=True
        )

    with col4:
        st.markdown(
            '<div class="kpi-card">'
            '<div class="kpi-title">Available Rooms</div>'
            '<div class="kpi-value">1</div>'
            '</div>',
            unsafe_allow_html=True
        )

    # TODAY'S SCHEDULE

    st.markdown(
        '<div class="section-title">📅 Today\'s Schedule</div>',
        unsafe_allow_html=True
    )

    for meeting in meetings:

        col1, col2, col3 = st.columns([2, 1, 1])

        with col1:
            st.markdown(
                f"**{meeting['title']}**"
            )

        with col2:
            st.markdown(
                f"🕐 {meeting['time']}"
            )

        with col3:
            st.markdown(
                f"🏢 {meeting['room']}"
            )

        st.divider()

    # ROOM OVERVIEW

    st.markdown(
        '<div class="section-title">🏢 Room Overview</div>',
        unsafe_allow_html=True
    )

    room_columns = st.columns(4)

    for index, room in enumerate(rooms):

        with room_columns[index]:

            if room["name"] in ["Room A", "Room B", "Room C"]:
                status = "Busy"
                status_class = "status-busy"
            else:
                status = "Available"
                status_class = "status-available"

            facilities = []

            if room["projector"]:
                facilities.append("Projector")

            if room["whiteboard"]:
                facilities.append("Whiteboard")

            facility_text = (
                ", ".join(facilities)
                if facilities
                else "No special facilities"
            )

            html = f"""
<div class="room-card">
<div class="room-name">{room["name"]}</div>
<div class="room-info">👥 Capacity: {room["capacity"]}</div>
<div class="room-info">🛠️ {facility_text}</div>
<br>
<div class="{status_class}">● {status}</div>
</div>
"""

            st.markdown(html, unsafe_allow_html=True)


# =========================================================
# MEETINGS PAGE
# =========================================================

elif page == "📅 Meetings":

    st.markdown(
        '<div class="main-title">Meetings</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">Manage and schedule your meetings.</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="section-title">➕ Book a New Meeting</div>',
        unsafe_allow_html=True
    )

    col1, col2 = st.columns(2)

    with col1:

        title = st.text_input(
            "Meeting Title",
            placeholder="e.g. Project Discussion"
        )

        meeting_date = st.date_input(
            "Date",
            value=date.today()
        )

        participants = st.number_input(
            "Number of Participants",
            min_value=1,
            max_value=100,
            value=2
        )

    with col2:

        start_time = st.time_input("Start Time")

        end_time = st.time_input("End Time")

        projector = st.checkbox("Projector Required")

        whiteboard = st.checkbox("Whiteboard Required")

    if st.button(
        "🔎 Find Best Room",
        use_container_width=True
    ):

        st.success(
            "Room allocation engine is ready. "
            "Database integration will be connected next."
        )


# =========================================================
# ROOMS PAGE
# =========================================================

elif page == "🏢 Rooms":

    st.markdown(
        '<div class="main-title">Meeting Rooms</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">View room capacity, facilities and availability.</div>',
        unsafe_allow_html=True
    )

    for room in rooms:

        facilities = []

        if room["projector"]:
            facilities.append("Projector")

        if room["whiteboard"]:
            facilities.append("Whiteboard")

        facility_text = (
            ", ".join(facilities)
            if facilities
            else "None"
        )

        html = f"""
<div class="room-card">
<div class="room-name">🏢 {room["name"]}</div>
<div class="room-info">👥 Capacity: {room["capacity"]}</div>
<div class="room-info">🛠️ Facilities: {facility_text}</div>
</div>
"""

        st.markdown(html, unsafe_allow_html=True)


# =========================================================
# SEARCH PAGE
# =========================================================

elif page == "🔍 Search":

    st.markdown(
        '<div class="main-title">Search Meetings</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">Find meetings by title, room or schedule.</div>',
        unsafe_allow_html=True
    )

    keyword = st.text_input(
        "Search",
        placeholder="Search meeting title..."
    )

    if keyword:

        results = [
            meeting
            for meeting in meetings
            if keyword.lower() in meeting["title"].lower()
        ]

        if results:

            for meeting in results:

                st.info(
                    f"**{meeting['title']}**  \n"
                    f"🕐 {meeting['time']}  |  "
                    f"🏢 {meeting['room']}  |  "
                    f"👥 {meeting['participants']} participants"
                )

        else:

            st.warning("No meetings found.")


# =========================================================
# SETTINGS PAGE
# =========================================================

elif page == "⚙️ Settings":

    st.markdown(
        '<div class="main-title">Settings</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">Application configuration.</div>',
        unsafe_allow_html=True
    )

    st.checkbox(
        "Enable conflict notifications",
        value=True
    )

    st.checkbox(
        "Enable best-fit room allocation",
        value=True
    )

    st.checkbox(
        "Show room availability",
        value=True
    )

    st.success(
        "SmartSpace configuration is ready."
    )